#Default Rules에서 비활성화할 규칙
disabled_rules:
    # 라인 뒤 공백 제거
    - trailing_whitespace
    - unneeded_override
    - unused_closure_parameter  
    
opt_in_rules:
    # 인덴트 룰 적용
    - indentation_width
    # 클로저의 끝 괄호를 시작한 행과의 들여쓰기 맞춤
    - closure_end_indentation
    # count보다 isEmpty 선호
    - empty_count
    # == ""보다 isEmpty 선호
    - empty_string
    # import 시 알파벳 순 정렬
    - sorted_imports
    
# 행 길이 커스텀 정의
line_length:
    warning: 200
    # URL에 대해 행 길이 제한 미적용
    ignores_urls: true
    # 코멘트에 대해 행 길이 제한 미적용
    ignores_comments: true
    # 보간된 문자열 행 길이 제한 미적용
    ignores_interpolated_strings: true
    # 메서드 선언부 행 길이 제한 미적용
    ignores_function_declarations: true
    
# 인덴트 커스텀 정의
indentation_width:
    indentation_width: 4
    include_comments: false
