# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TwitterClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TwitterClone

  $FirebaseSDKVersion = '10.16.0'
	pod 'Firebase/Core', $FirebaseSDKVersion
	pod 'Firebase/Database', $FirebaseSDKVersion
	pod 'Firebase/Storage', $FirebaseSDKVersion
	pod 'Firebase/Auth', $FirebaseSDKVersion
  	pod 'SDWebImage', '~> 5.0'

end
